### ISSUE TITLE
Siren doesn't build

### ISSUE THREAD

**Issue by ldodds** [rdelbru/SIREn#75]
Hi,

I've just downloaded RC3 and also tried checking out the main code branch. In both cases the maven build fails because of a badly configured dependency on caliper.

Looking in the mailing list, there's a potential resolution here:

http://lists.deri.org/pipermail/siren/2012-October/000303.html

However the pom.xml suggested there doesn't fix the problem either.

Is Siren still a live active project? The fact that it doesn't build out of the box and that there are no commits for nearly a year suggests it isn't.

Before investing further time/effort in the project it'd be useful to know whether it is still undergoing active development. Is the version in use at Sindice different to this project?

**Comment by rdelbru** [comment]
Hi Leigh

On 07/11/12 16:58, Leigh Dodds wrote:

> Hi,
> 
> I've just downloaded RC3 and also tried checking out the main code
> branch. In both cases the maven build fails because of a badly
> configured dependency on caliper.
> 
> Looking in the mailing list, there's a potential resolution here:
> 
> http://lists.deri.org/pipermail/siren/2012-October/000303.html
> 
> However the pom.xml suggested there doesn't fix the problem either.

Yes, the problem with caliper comes from the fact they removed the 
snapshot dependency after we released siren. And since we do not 
maintain siren 0.2.x anymore, we have not updated the pom.xml accordingly.

Normally the fixes given is the mail you reference should have solved 
the issue. Could you please provide us the error you encounter ?

> Is Siren still a live active project? The fact that it doesn't build out
> of the box and that there are no commits for nearly a year suggests it
> isn't.
> 
> Before investing further time/effort in the project it'd be useful to
> know whether it is still undergoing active development. Is the version
> in use at Sindice different to this project?

SIREn 0.2.3 is the version currently in use in Sindice.

SIREn 0.2.x is not maintained anymore, and it is why you do not see any 
new commits since one year. All our efforts is currently focussed on the 
1.0 version, but its project repository is currently private. As 
explained in a previous mail, we might release a new open-source version 
in the close future [1].

[1] http://lists.deri.org/pipermail/siren/2012-October/000298.html

## Kind Regards

Renaud Delbru
